## Import the Library

In [2]:
import numpy as np

In [3]:
list = [1, 2, 3, 4, 5]

In [4]:
numpy_list = np.array(list)

In [5]:
numpy_list

array([1, 2, 3, 4, 5])

### 2-dimensional array

In [10]:
two_d_list = [[1,1,3], [6,3,9], [2,5,6]]

In [11]:
two_d_arr = np.array(two_d_list)

In [12]:
two_d_arr

array([[1, 1, 3],
       [6, 3, 9],
       [2, 5, 6]])

### arange() - Function

In [14]:
list = np.arange(10)  
list

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
list = np.arange(0,11,2)
list

array([ 0,  2,  4,  6,  8, 10])

### zero() - Function

In [17]:
list_zeros = np.zeros(6)
list_zeros

array([0., 0., 0., 0., 0., 0.])

In [19]:
list_2d = np.zeros((3,4))
list_2d

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### ones() - Function

In [18]:
list_ones = np.ones(6)
list_ones

array([1., 1., 1., 1., 1., 1.])

### random.rand() - Function

In [21]:
rand = np.random.rand(5)
rand

array([0.56383777, 0.40232783, 0.44717072, 0.13706495, 0.13139174])

In [22]:
rand = np.random.rand(4, 5)
rand

array([[0.27952355, 0.89231763, 0.2504324 , 0.02417606, 0.23487391],
       [0.71007372, 0.87521911, 0.62969439, 0.27101095, 0.98811877],
       [0.22090329, 0.6228323 , 0.02321704, 0.65018174, 0.26722788],
       [0.44404895, 0.40151692, 0.59004932, 0.71915037, 0.71880091]])

### max() and min() - Functions

In [25]:
arr_2 = np.random.randint(0, 20, 10) 
arr_2

array([18, 14, 13, 13,  7,  4,  6,  3, 19,  0])

In [26]:
arr_2.max() 

19

In [27]:
arr_2.min()

0

In [30]:
arr_2 = np.random.randint(0, 20, 10) 
arr_2

array([ 0,  1,  1, 10,  6, 12,  4,  7, 12, 14])

In [28]:
arr_2.argmax() 

8

In [29]:
arr_2.argmin() 

9

In [34]:
np_array = np.arange(0,10)
np_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
a = np_array[2:4] 
a

array([2, 3])

In [36]:
b = np_array[:5] 
b

array([0, 1, 2, 3, 4])

In [37]:
c = np_array[6:] 
c

array([6, 7, 8, 9])

In [42]:
np_array = np.arange(0,10)
np_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
np_array[9]  

9

### Conditional Operators

In [47]:
my_arr = np.arange(6,14)
my_arr

array([ 6,  7,  8,  9, 10, 11, 12, 13])

In [48]:
my_arr > 10 

array([False, False, False, False, False,  True,  True,  True])

In [49]:
bool_arr = my_arr > 10

In [50]:
my_arr[bool_arr]  

array([11, 12, 13])

In [51]:
my_arr[(my_arr>5) & (my_arr<10)]

array([6, 7, 8, 9])

### Creating matrices

In [53]:
data = np.array([[1, 2], [3, 4]])
data

array([[1, 2],
       [3, 4]])

### np.unique() - Function

In [54]:
b = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [56]:
unique_values = np.unique(b)
unique_values

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

### transpose() - Function

In [58]:
arr = np.arange(6).reshape((2, 3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [59]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [61]:
arr.reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

### How to create an array from existing data

In [62]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [65]:
a1 = np.array([[1, 1],
                [2, 2]])
a2 = np.array([[3, 3],
            [4, 4]])


In [66]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [67]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])